Develop
dd-obua/Hello-world pull request #1
Opened 2022-02-09 21:28 UTC by dd-obua

Configured linters on Hello Microverse project

2022-02-09 21:52 UTC, Whoistolu requested changes
Hi @dd-obua,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

_Check the inline comments under the review for sections to improve._

### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

#### N/A

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-02-09 21:52 UTC, Whoistolu commented on index.html
> +</html>
- [ ] [REQUIRED] One of the requirements states that linters need to be set up correctly on this repository. Kindly ensure that all linters pass (Showing the green ticks). Please implement this. Linters help us ensure code standards.  Check this [Linters article](https://github.com/microverseinc/linters-config) for more explanations.
- [ ] [REQUIRED] Also note that your Pull Request should have a descriptive title telling you what changes are inside and its description should have a short summary describing introduced changes in more detail. Check [this link](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) for more detail. This will make your project look more professional.

2022-02-09 21:52 UTC, Whoistolu commented on .gitignore
> +node_modules/
- [ ] [REQUIRED] Please note that you need to add `test.md` file to the `gitignore file`. This is a professional practice that ensures those files are not pushed to github.

2022-02-10 08:08 UTC, thecodechaser approved these changes
## Hi @dd-obua 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-10 09:17 UTC, merged